# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pycast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_article', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('text_article', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
