# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pycast', '0003_auto_20170223_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='blog/uploads/postagem'),
        ),
    ]
