# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pycast', '0004_post_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='static/uploads/postagem'),
        ),
    ]
